# Generated by Django 5.2 on 2025-04-19 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField()),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=10)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('rps', models.PositiveIntegerField(help_text='Requests per second')),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'load_test',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sim',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LoadTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_time_avg', models.FloatField(help_text='Average response time in milliseconds')),
                ('success_rate', models.FloatField(help_text='Success rate as a percentage')),
                ('error_rate', models.FloatField(help_text='Error rate as a percentage')),
                ('status_distribution', models.JSONField(help_text='Distribution of HTTP status codes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='load_simulator.loadtest')),
            ],
            options={
                'db_table': 'load_test_result',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='loadtest',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_tests', to='load_simulator.sim'),
        ),
    ]
