# Generated by Django 5.2 on 2025-04-28 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='메시지 본문 (템플릿)')),
                ('notification_type', models.IntegerField(choices=[(0, 'SMS'), (1, '알림톡'), (2, '메일')])),
                ('template_code', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='가상 유저 이름', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoadTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='부하 테스트할 대상 URL')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('body', models.JSONField(blank=True, help_text='요청에 포함할 JSON 데이터', null=True)),
                ('headers', models.JSONField(blank=True, help_text='요청 헤더', null=True)),
                ('start_time', models.DateTimeField(help_text='테스트 시작 시각')),
                ('duration', models.PositiveIntegerField(default=1, help_text='테스트 지속 시간 (초)')),
                ('concurrent_users', models.PositiveIntegerField(default=1, help_text='동시 사용자 수')),
                ('requests_count', models.PositiveIntegerField(default=1, help_text='한 유저당 요청 수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='이 테스트를 생성한 유저', on_delete=django.db.models.deletion.CASCADE, related_name='load_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='발송된 메시지 내용')),
                ('is_success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('notification_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='load_simulator.notificationtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=255)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('body', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_steps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioStepOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('is_optional', models.BooleanField(default=False)),
                ('weight', models.FloatField(default=1.0)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='load_simulator.scenariosteporder')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_orders', to='load_simulator.scenario')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='load_simulator.scenariostep')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('scenario', 'order')},
            },
        ),
    ]
