# Generated by Django 5.2 on 2025-05-07 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='가상 유저 이름', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sim',
            },
        ),
        migrations.CreateModel(
            name='LoadTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='부하 테스트 할 대상 URL', max_length=255)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('body', models.JSONField(blank=True, help_text='요청에 포함할 JSON 데이터', null=True)),
                ('headers', models.JSONField(blank=True, help_text='요청 헤더', null=True)),
                ('start_time', models.DateTimeField(help_text='테스트 시작 시각')),
                ('duration', models.PositiveIntegerField(default=1, help_text='테스트 지속 시간 (초)')),
                ('concurrent_users', models.PositiveIntegerField(default=1, help_text='동시 사용자 수')),
                ('requests_count', models.PositiveIntegerField(default=1, help_text='한 유저당 요청 수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='이 테스트를 생성한 유저', on_delete=django.db.models.deletion.CASCADE, related_name='load_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'load_test',
                'ordering': ['-created_at'],
            },
        ),
    ]
