# Generated by Django 5.2 on 2025-04-28 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loadtest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notificationhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='loadtest',
            table='load_test',
        ),
        migrations.AlterModelTable(
            name='notificationhistory',
            table='notification_history',
        ),
        migrations.AlterModelTable(
            name='notificationtemplate',
            table='notification_template',
        ),
        migrations.AlterModelTable(
            name='scenario',
            table='scenario',
        ),
        migrations.AlterModelTable(
            name='scenariostep',
            table='scenario_step',
        ),
        migrations.AlterModelTable(
            name='scenariosteporder',
            table='scenario_step_order',
        ),
        migrations.AlterModelTable(
            name='sim',
            table='sim',
        ),
    ]
